### ISSUE TITLE
can't scroll when using fullscreen canvas

### ISSUE THREAD

**Issue by szymonkaliski** [variablestudio/pex-sys#5]
When building a website with pex in fullscreen mode as "splash screen":

```
+--------------+
|              |
| CANVAS [pex] |
|              |
+--------------+
|              |
|              |
|   CONTENT    |
|              |
|              |
+--------------+

```

User can't scroll to CONTENT because of:

1. CANVAS set to 100% of height and width
2. pex setting `overflow: hidden` on body (this can be fixed in CSS with `body { overflow: scroll !important }`
3. pex doing `preventDefault()` on `touchmove` events which blocks scrolling on mobile devices

Ideally scrolling/draggin would move CANVAS and CONTENT up so users can see the content :)

I'm not really sure what would be a desired behavior? Maybe we should declare which events pex should handle in settings (and handle all by default)? Then if I only want mouseMoved I would do `events: [ "mouseMoved" ]`?

**Comment by vorg** [comment]
This will be addressed in the new version of pex-sys
